const languages = {
    en: {
        home: "Home",
        about: "About Us",
        history: "History",
        services: "Services",
        partners: "Partners",
        contact: "Contact",
        heroTitle: "Pioneering Solutions for a Digital Age",
        heroSubtitle: "Expert consulting in Cybersecurity, AI, and Multimedia.",
        discoverServices: "Discover Our Services",
        aboutTitle: "About Us",
        aboutSubtitle: "Our Vision, Mission, and Values",
        vision: "<strong>Vision:</strong> To be the leading global partner for organizations navigating the complexities of the digital frontier.",
        mission: "<strong>Mission:</strong> To empower our clients with strategic insights and transformative solutions in cybersecurity, artificial intelligence, and digital media.",
        values: "<strong>Values:</strong> Integrity, Innovation, and Excellence form the bedrock of our operations and client relationships.",
        historyTitle: "Our History",
        historySubtitle: "The Journey of Grafamara",
        historyText: "Founded in 2020, Grafamara began with a singular mission: to demystify the digital world for businesses of all sizes. From our origins as a small cybersecurity consultancy, we have grown into a multi-faceted agency, driven by a passion for technology and a commitment to client success. Our journey is one of continuous evolution, always staying ahead of the curve to deliver unparalleled expertise.",
        servicesTitle: "Our Services",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Strategic guidance in Cybersecurity, AI, and Risk Management to protect and future-proof your business.",
        advisoryExample: "<em>Example: AI Integration Audit & Penetration Testing.</em>",
        advisoryServicesInclude: "Our Advisory Services Include:",
        advisoryService1: "<strong>Cybersecurity Strategy & Implementation:</strong> Developing comprehensive security frameworks, implementing advanced protection systems, and ensuring compliance with international standards (e.g., GDPR, ISO 27001).",
        advisoryService2: "<strong>AI Integration Audit & Ethics:</strong> Assessing the security implications of AI adoption, auditing AI systems for biases and vulnerabilities, and establishing ethical AI guidelines.",
        advisoryService3: "<strong>Risk Management & Business Continuity:</strong> Identifying potential digital risks, developing mitigation strategies, and creating robust business continuity plans to minimize disruption.",
        advisoryService4: "<strong>Penetration Testing & Vulnerability Assessments:</strong> Proactively identifying weaknesses in your systems and applications through simulated attacks and thorough security evaluations.",
        advisoryService5: "<strong>Security Awareness Training:</strong> Empowering your employees with the knowledge and skills to recognize and respond to cyber threats, turning your workforce into your strongest defense.",
        whyChooseAdvisory: "Why Choose Grafamara Advisory?",
        whyChooseAdvisoryText: "Our team of certified cybersecurity and AI experts brings deep industry knowledge and a proactive approach to digital defense. We don't just identify problems; we provide actionable strategies and hands-on support to implement lasting solutions. Partner with us to transform your digital vulnerabilities into strategic strengths.",
        requestConsultation: "Request a Cybersecurity Consultation",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Personal and professional development programs designed to unlock potential and drive success.",
        coachingExample: "<em>Exemple : Coaching de dirigeants et parcours de croissance personnelle.</em>",
        coachingProgramsInclude: "Nos Programmes de Coaching Comprennent :",
        coachingProgram1: "<strong>Coaching Exécutif :</strong> Coaching individuel pour les leaders et les cadres afin d'affiner les compétences en leadership, d'améliorer la prise de décision et de renforcer la pensée stratégique.",
        coachingProgram2: "<strong>Parcours de Croissance Personnelle :</strong> Programmes personnalisés pour les individus cherchant à développer des compétences spécifiques, à surmonter les obstacles et à atteindre des jalons personnels.",
        coachingProgram3: "<strong>Développement et Cohésion d'Équipe :</strong> Ateliers et séances de coaching axés sur l'amélioration de la dynamique d'équipe, de la communication, de la collaboration et de la performance collective.",
        coachingProgram4: "<strong>Coaching en Gestion du Changement :</strong> Accompagnement des organisations et des individus à travers les périodes de transition, assurant une adaptation en douceur et une mise en œuvre réussie des nouvelles stratégies.",
        coachingProgram5: "<strong>Ateliers d'Innovation et de Créativité :</strong> Favoriser une culture de l'innovation au sein de votre organisation, encourageant la résolution créative de problèmes et la pensée hors des sentiers battus.",
        whyChooseCoaching: "Pourquoi Choisir Grafamara Coaching ?",
        whyChooseCoachingText: "Nos coachs certifiés apportent une richesse d'expérience et une compréhension approfondie du potentiel humain. Nous utilisons des méthodologies éprouvées et une approche personnalisée, garantissant que chaque programme est aligné sur vos objectifs uniques. Que vous soyez un leader en herbe, un cadre chevronné ou une équipe cherchant à améliorer ses performances, Grafamara Coaching est votre partenaire pour une transformation durable.",
        exploreCoachingPrograms: "Explorez Nos Programmes de Coaching",
        multimediaTitle: "Grafamara Multimedia",
        coachingProgramsInclude: "Our Coaching Programs Include:",
        coachingProgram1: "<strong>Executive Coaching:</strong> One-on-one coaching for leaders and executives to refine leadership skills, improve decision-making, and enhance strategic thinking.",
        coachingProgram2: "<strong>Personal Growth Paths:</strong> Customized programs for individuals seeking to develop specific skills, overcome obstacles, and achieve personal milestones.",
        coachingProgram3: "<strong>Team Development & Cohesion:</strong> Workshops and coaching sessions focused on improving team dynamics, communication, collaboration, and collective performance.",
        coachingProgram4: "<strong>Change Management Coaching:</strong> Guiding organizations and individuals through periods of transition, ensuring smooth adaptation and successful implementation of new strategies.",
        coachingProgram5: "<strong>Innovation & Creativity Workshops:</strong> Fostering a culture of innovation within your organization, encouraging creative problem-solving and out-of-the-box thinking.",
        whyChooseCoaching: "Why Choose Grafamara Coaching?",
        whyChooseCoachingText: "Our certified coaches bring a wealth of experience and a deep understanding of human potential. We employ proven methodologies and a personalized approach, ensuring that each program is aligned with your unique objectives. Whether you are an aspiring leader, a seasoned executive, or a team looking to elevate its performance, Grafamara Coaching is your partner in achieving lasting transformation.",
        exploreCoachingPrograms: "Explore Our Coaching Programs",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Consulting for modern media platforms, including YouTube, blogs, and podcasts, to build your brand's voice.",
        multimediaExample: "<em>Example: YouTube Channel Growth Strategy.</em>",
        multimediaServicesInclude: "Our Multimedia Services Include:",
        multimediaService1: "<strong>YouTube Channel Management & Growth Strategy:</strong> We offer end-to-end support for your YouTube presence, including content strategy, video production guidance, SEO optimization, audience engagement, and growth analytics. Our success with **Bosolo TV**, growing from 0 to over 500,000 subscribers, is a testament to our expertise.",
        multimediaService2: "<strong>Podcast Production & Distribution:</strong> From concept development and scriptwriting to recording, editing, and distribution, we handle every aspect of podcast creation, ensuring high-quality audio and broad reach.",
        multimediaService3: "<strong>Blog Content Creation & Strategy:</strong> Crafting engaging and SEO-optimized blog posts that resonate with your target audience, drive traffic, and establish your thought leadership.",
        multimediaService4: "<strong>Technical Setup & Studio Optimization:</strong> Assisting with the setup of professional recording studios, recommending equipment, and optimizing your technical workflow for seamless content production.",
        multimediaService5: "<strong>Digital Media Consulting:</strong> Providing strategic advice on leveraging various digital media platforms to achieve your communication and marketing objectives.",
        whyChooseMultimedia: "Why Choose Grafamara Multimedia?",
        whyChooseMultimediaText: "Our team combines creative vision with technical expertise to deliver multimedia solutions that stand out. We understand the nuances of digital storytelling and audience engagement, ensuring your content not only reaches but also captivates your target market. Partner with Grafamara Multimedia to transform your ideas into influential digital experiences.",
        discussMultimediaProject: "Discuss Your Multimedia Project",
        contactTitle: "Contact Us",
        lastName: "Last Name:",
        firstName: "First Name:",
        email: "Email Address:",
        phone: "Phone Number:",
        sendMessage: "Send Message",
        partnersTitle: "Our Partners",
        kashandel: "Kashandel",
        kashandelText: "A leading provider of innovative business solutions.",
        absy: "ABSY TV",
        absyText: "Your source for engaging and high-quality video content.",
        sam: "8Sam.ev",
        samText: "Pioneering the future of event management technology.",
        copyright: "&copy; 2025 Grafamara. All Rights Reserved.",
        ourPartners: "Our Partners:"
    },
    fr: {
        home: "Accueil",
        about: "À propos",
        history: "Notre histoire",
        services: "Nos services",
        partners: "Nos partenaires",
        contact: "Contact",
        heroTitle: "Des solutions pionnières pour une ère numérique",
        heroSubtitle: "Conseil expert en cybersécurité, IA et multimédia.",
        discoverServices: "Découvrez nos services",
        aboutTitle: "À propos de nous",
        aboutSubtitle: "Notre vision, notre mission et nos valeurs",
        vision: "<strong>Vision :</strong> Être le principal partenaire mondial des organisations qui naviguent dans les complexités de la frontière numérique.",
        mission: "<strong>Mission :</strong> Donner à nos clients les moyens d'obtenir des informations stratégiques et des solutions transformatrices en matière de cybersécurité, d'intelligence artificielle et de médias numériques.",
        values: "<strong>Valeurs :</strong> L'intégrité, l'innovation et l'excellence constituent le fondement de nos opérations et de nos relations avec nos clients.",
        historyTitle: "Notre histoire",
        historySubtitle: "Le parcours de Grafamara",
        historyText: "Fondée en 2020, Grafamara a commencé avec une mission singulière : démystifier le monde numérique pour les entreprises de toutes tailles. Depuis nos origines en tant que petite société de conseil en cybersécurité, nous sommes devenus une agence aux multiples facettes, animée par une passion pour la technologie et un engagement envers la réussite de nos clients. Notre parcours est celui d'une évolution continue, toujours à la pointe du progrès pour offrir une expertise inégalée.",
        servicesTitle: "Nos services",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Conseils stratégiques en matière de cybersécurité, d'IA et de gestion des risques pour protéger et pérenniser votre entreprise.",
        advisoryExample: "<em>Exemple : Audit d'intégration de l'IA et tests de pénétration.</em>",
        advisoryServicesInclude: "Nos Services de Conseil Comprennent :",
        advisoryService1: "<strong>Stratégie et Mise en Œuvre de la Cybersécurité :</strong> Développement de cadres de sécurité complets, mise en œuvre de systèmes de protection avancés et garantie de la conformité aux normes internationales (par exemple, RGPD, ISO 27001).",
        advisoryService2: "<strong>Audit et Éthique de l'Intégration de l'IA :</strong> Évaluation des implications de sécurité de l'adoption de l'IA, audit des systèmes d'IA pour les biais et les vulnérabilités, et établissement de directives éthiques en matière d'IA.",
        advisoryService3: "<strong>Gestion des Risques et Continuité des Activités :</strong> Identification des risques numériques potentiels, élaboration de stratégies d'atténuation et création de plans de continuité des activités robustes pour minimiser les perturbations.",
        advisoryService4: "<strong>Tests d'Intrusion et Évaluations des Vulnérabilités :</strong> Identification proactive des faiblesses de vos systèmes et applications par le biais d'attaques simulées et d'évaluations de sécurité approfondies.",
        advisoryService5: "<strong>Formation de Sensibilisation à la Sécurité :</strong> Donner à vos employés les connaissances et les compétences nécessaires pour reconnaître et réagir aux cybermenaces, transformant ainsi votre personnel en votre plus forte défense.",
        whyChooseAdvisory: "Pourquoi Choisir Grafamara Advisory ?",
        whyChooseAdvisoryText: "Notre équipe d'experts certifiés en cybersécurité et en IA apporte une connaissance approfondie de l'industrie et une approche proactive de la défense numérique. Nous ne nous contentons pas d'identifier les problèmes ; nous fournissons des stratégies exploitables et un soutien pratique pour mettre en œuvre des solutions durables. Partenaires avec nous pour transformer vos vulnérabilités numériques en atouts stratégiques.",
        requestConsultation: "Demandez une Consultation en Cybersécurité",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Programmes de développement personnel et professionnel conçus pour libérer le potentiel et favoriser la réussite.",
        coachingExample: "<em>Exemple : Coaching de dirigeants et parcours de croissance personnelle.</em>",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Conseil pour les plateformes médiatiques modernes, y compris YouTube, les blogs et les podcasts, afin de développer la voix de votre marque.",
        multimediaExample: "<em>Exemple : Stratégie de croissance et de mise en place d'une chaîne YouTube.</em>",
        contactTitle: "Contactez-nous",
        lastName: "Nom de famille :",
        firstName: "Prénom :",
        email: "Adresse électronique :",
        phone: "Numéro de téléphone :",
        sendMessage: "Envoyer le message",
        partnersTitle: "Nos partenaires",
        kashandel: "Kashandel",
        kashandelText: "Un fournisseur de premier plan de solutions commerciales innovantes.",
        absy: "ABSY TV",
        absyText: "Votre source de contenu vidéo engageant et de haute qualité.",
        sam: "8Sam.ev",
        samText: "Pionnier de l'avenir de la technologie de gestion d'événements.",
        copyright: "&copy; 2025 Grafamara. Tous droits réservés.",
        ourPartners: "Nos partenaires :"
    },
    de: {
        home: "Startseite",
        about: "Über uns",
        history: "Unsere Geschichte",
        services: "Unsere Dienstleistungen",
        partners: "Unsere Partner",
        contact: "Kontakt",
        heroTitle: "Wegweisende Lösungen für ein digitales Zeitalter",
        heroSubtitle: "Kompetente Beratung in den Bereichen Cybersicherheit, KI und Multimedia.",
        discoverServices: "Entdecken Sie unsere Dienstleistungen",
        aboutTitle: "Über uns",
        aboutSubtitle: "Unsere Vision, Mission und Werte",
        vision: "<strong>Vision:</strong> Der führende globale Partner für Unternehmen zu sein, die sich in der Komplexität der digitalen Welt bewegen.",
        mission: "<strong>Mission:</strong> Unsere Kunden mit strategischen Einblicken und transformativen Lösungen in den Bereichen Cybersicherheit, künstliche Intelligenz und digitale Medien zu unterstützen.",
        values: "<strong>Werte:</strong> Integrität, Innovation und Exzellenz bilden das Fundament unserer Tätigkeit und unserer Kundenbeziehungen.",
        historyTitle: "Unsere Geschichte",
        historySubtitle: "Die Reise von Grafamara",
        historyText: "Grafamara wurde 2020 mit einer einzigen Mission gegründet: die digitale Welt für Unternehmen jeder Größe zu entmystifizieren. Von unseren Anfängen als kleines Beratungsunternehmen für Cybersicherheit haben wir uns zu einer facettenreichen Agentur entwickelt, die von einer Leidenschaft für Technologie und dem Engagement für den Erfolg unserer Kunden angetrieben wird. Unser Weg ist ein Weg der kontinuierlichen Weiterentwicklung, bei dem wir immer einen Schritt voraus sind, um unübertroffenes Fachwissen zu liefern.",
        servicesTitle: "Unsere Dienstleistungen",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Strategische Beratung in den Bereichen Cybersicherheit, KI und Risikomanagement zum Schutz und zur Zukunftssicherheit Ihres Unternehmens.",
        advisoryExample: "<em>Beispiel: KI-Integrationsprüfung und Penetrationstests.</em>",
        advisoryServicesInclude: "Unsere Beratungsleistungen umfassen:",
        advisoryService1: "<strong>Cybersicherheitsstrategie & Implementierung:</strong> Entwicklung umfassender Sicherheitsrahmen, Implementierung fortschrittlicher Schutzsysteme und Sicherstellung der Einhaltung internationaler Standards (z.B. DSGVO, ISO 27001).",
        advisoryService2: "<strong>KI-Integrationsprüfung & Ethik:</strong> Bewertung der Sicherheitsauswirkungen der KI-Einführung, Prüfung von KI-Systemen auf Verzerrungen und Schwachstellen sowie Festlegung ethischer KI-Richtlinien.",
        advisoryService3: "<strong>Risikomanagement & Geschäftskontinuität:</strong> Identifizierung potenzieller digitaler Risiken, Entwicklung von Minderungsstrategien und Erstellung robuster Geschäftskontinuitätspläne zur Minimierung von Unterbrechungen.",
        advisoryService4: "<strong>Penetrationstests & Schwachstellenanalysen:</strong> Proaktive Identifizierung von Schwachstellen in Ihren Systemen und Anwendungen durch simulierte Angriffe und gründliche Sicherheitsbewertungen.",
        advisoryService5: "<strong>Schulungen zur Sicherheitsbewusstsein:</strong> Befähigung Ihrer Mitarbeiter mit dem Wissen und den Fähigkeiten, Cyberbedrohungen zu erkennen und darauf zu reagieren, wodurch Ihre Belegschaft zu Ihrer stärksten Verteidigung wird.",
        whyChooseAdvisory: "Warum Grafamara Advisory wählen?",
        whyChooseAdvisoryText: "Unser Team aus zertifizierten Cybersicherheits- und KI-Experten verfügt über fundiertes Branchenwissen und einen proaktiven Ansatz zur digitalen Verteidigung. Wir identifizieren nicht nur Probleme; wir bieten umsetzbare Strategien und praktische Unterstützung bei der Implementierung dauerhafter Lösungen. Arbeiten Sie mit uns zusammen, um Ihre digitalen Schwachstellen in strategische Stärken zu verwandeln.",
        requestConsultation: "Fordern Sie eine Cybersicherheitsberatung an",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Programme zur persönlichen und beruflichen Entwicklung, die darauf abzielen, Potenziale freizusetzen und den Erfolg zu fördern.",
        coachingExample: "<em>Beispiel: Executive Coaching & Personal Growth Paths.</em>",
        coachingProgramsInclude: "Unsere Coaching-Programme umfassen:",
        coachingProgram1: "<strong>Executive Coaching:</strong> Einzelcoaching für Führungskräfte und Manager zur Verfeinerung von Führungsqualitäten, Verbesserung der Entscheidungsfindung und Stärkung des strategischen Denkens.",
        coachingProgram2: "<strong>Persönliche Wachstumswege:</strong> Maßgeschneiderte Programme für Einzelpersonen, die spezifische Fähigkeiten entwickeln, Hindernisse überwinden und persönliche Meilensteine erreichen möchten.",
        coachingProgram3: "<strong>Teamentwicklung & Zusammenhalt:</strong> Workshops und Coaching-Sitzungen zur Verbesserung der Teamdynamik, Kommunikation, Zusammenarbeit und kollektiven Leistung.",
        coachingProgram4: "<strong>Change Management Coaching:</strong> Begleitung von Organisationen und Einzelpersonen durch Übergangsphasen, um eine reibungslose Anpassung und erfolgreiche Umsetzung neuer Strategien zu gewährleisten.",
        coachingProgram5: "<strong>Innovations- und Kreativitäts-Workshops:</strong> Förderung einer Innovationskultur in Ihrem Unternehmen, Ermutigung zu kreativer Problemlösung und unkonventionellem Denken.",
        whyChooseCoaching: "Warum Grafamara Coaching wählen?",
        whyChooseCoachingText: "Unsere zertifizierten Coaches verfügen über einen reichen Erfahrungsschatz und ein tiefes Verständnis des menschlichen Potenzials. Wir wenden bewährte Methoden und einen personalisierten Ansatz an, um sicherzustellen, dass jedes Programm auf Ihre individuellen Ziele abgestimmt ist. Ob Sie eine aufstrebende Führungskraft, ein erfahrener Manager oder ein Team sind, das seine Leistung steigern möchte, Grafamara Coaching ist Ihr Partner für eine dauerhafte Transformation.",
        exploreCoachingPrograms: "Entdecken Sie unsere Coaching-Programme",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Beratung für moderne Medienplattformen, einschließlich YouTube, Blogs und Podcasts, um die Stimme Ihrer Marke aufzubauen.",
        multimediaExample: "<em>Beispiel: Einrichtungs- und Wachstumsstrategie für YouTube-Kanäle.</em>",
        contactTitle: "Kontaktieren Sie uns",
        lastName: "Nachname:",
        firstName: "Vorname:",
        email: "E-Mail-Adresse:",
        phone: "Telefonnummer:",
        sendMessage: "Nachricht senden",
        partnersTitle: "Unsere Partner",
        kashandel: "Kashandel",
        kashandelText: "Ein führender Anbieter von innovativen Geschäftslösungen.",
        absy: "ABSY TV",
        absyText: "Ihre Quelle für ansprechende und qualitativ hochwertige Videoinhalte.",
        sam: "8Sam.ev",
        samText: "Wegbereiter für die Zukunft der Event-Management-Technologie.",
        copyright: "&copy; 2025 Grafamara. Alle Rechte vorbehalten.",
        ourPartners: "Unsere Partner:"
    }
};