const languages = {
    en: {
        home: "Home",
        about: "About Us",
        history: "History",
        services: "Services",
        partners: "Partners",
        contact: "Contact",
        heroTitle: "Grafamara: Your Bridge to Digital Excellence",
        heroSubtitle: "Pioneering Solutions for a Connected World",
        discoverServices: "Discover Our Services",
        aboutTitle: "About Us",
        aboutSubtitle: "Our Commitment: Building Digital Bridges",
        aboutParagraph1: "At <b>Grafamara</b>, we are more than an IT consulting firm — we are <b>architects of transformation</b>, <b>catalysts for growth</b>, and <b>builders of cross-continental connections</b>.",
        aboutParagraph2: "Founded in <b>Germany in 2017</b>, Grafamara has rapidly emerged as a trusted player in the consulting landscape, thanks to a sharp focus on <b>innovation</b>, <b>reliability</b>, and a solid grasp of <b>global market dynamics</b>. Our team of passionate experts turns complex technological challenges into strategic opportunities tailored to your vision and goals.",
        aboutParagraph3: "What sets us apart is our <b>unique positioning at the crossroads of Europe and Africa</b>. We are deeply convinced of the vast, untapped potential of the <b>Democratic Republic of Congo (DRC)</b> — a vibrant nation with a young, connected population and a strong appetite for digital innovation.",
        aboutParagraph4: "Grafamara is committed to fostering <b>sustainable partnerships</b>, enabling European businesses and institutions to <b>explore and invest</b> in the emerging opportunities across the DRC. At the same time, we empower <b>Congolese enterprises and public institutions</b> to achieve <b>digital excellence</b> and align with <b>global best practices</b>.",
        aboutParagraph5: "In addition, we offer <b>personalized guidance</b> to all individuals and entrepreneurs who wish to <b>invest, collaborate, buy or sell with European companies</b>. Whether you are looking to establish a partnership, pursue academic opportunities, open a bank account, apply for a visa, or launch a business venture — <b>Grafamara will be by your side from day one</b>. We help you <b>navigate administrative processes</b> with clarity and ensure you make the right moves from the start.",
        aboutParagraph6: "Our work is grounded in <b>four core values</b>:<br> <b>Integrity</b> — Transparent advice rooted in trust and ethics<br> <b>Innovation</b> — Creative, future-proof, and user-centric solutions<br> <b>Excellence</b> — High standards in every project and every partnership<br> <b>Partnership</b> — Long-term collaborations that create real impact",
        aboutParagraph7: "By choosing Grafamara, you choose a <b>partner who not only understands your technical needs</b>, but who is also <b>deeply connected to the cultural, social, and economic realities of the regions we serve</b>.",
        aboutParagraph8: "Let us help you navigate the future with clarity, confidence, and success.",
        historyTitle: "Our History",
        historySubtitle: "From 2017 to Today: Building the Digital Future",
        historyText: "The Grafamara adventure began in 2017 in Germany, driven by a clear vision: to demystify technology and make it accessible, secure, and profitable for everyone. What started as a passionate initiative quickly transformed into a recognized IT consulting firm, thanks to our unwavering commitment to excellence and innovation. From our early days, we focused on cybersecurity, anticipating the challenges of an increasingly connected world.",
        servicesTitle: "Our Services",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Strategic guidance in Cybersecurity, AI, and Risk Management to protect and future-proof your business.",
        advisoryExample: "<em>Example: AI Integration Audit & Penetration Testing.</em>",
        advisoryServicesInclude: "Our Advisory Services Include:",
        advisoryService1: "<strong>Cybersecurity Strategy & Implementation:</strong> Developing comprehensive security frameworks, implementing advanced protection systems, and ensuring compliance with international standards (e.g., GDPR, ISO 27001).",
        advisoryService2: "<strong>AI Integration Audit & Ethics:</strong> Assessing the security implications of AI adoption, auditing AI systems for biases and vulnerabilities, and establishing ethical AI guidelines.",
        advisoryService3: "<strong>Risk Management & Business Continuity:</strong> Identifying potential digital risks, developing mitigation strategies, and creating robust business continuity plans to minimize disruption.",
        advisoryService4: "<strong>Penetration Testing & Vulnerability Assessments:</strong> Proactively identifying weaknesses in your systems and applications through simulated attacks and thorough security evaluations.",
        advisoryService5: "<strong>Security Awareness Training:</strong> Empowering your employees with the knowledge and skills to recognize and respond to cyber threats, turning your workforce into your strongest defense.",
        whyChooseAdvisory: "Why Choose Grafamara Advisory?",
        whyChooseAdvisoryText: "Our team of certified cybersecurity and AI experts brings deep industry knowledge and a proactive approach to digital defense. We don't just identify problems; we provide actionable strategies and hands-on support to implement lasting solutions. Partner with us to transform your digital vulnerabilities into strategic strengths.",
        requestConsultation: "Request a Cybersecurity Consultation",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Personal and professional development programs designed to unlock potential and drive success.",
        coachingExample: "<em>Example: Executive Coaching & Personal Growth Paths.</em>",
        coachingProgramsInclude: "Our Coaching Programs Include:",
        coachingProgram1: "<strong>Executive Coaching:</strong> One-on-one coaching for leaders and executives to refine leadership skills, improve decision-making, and enhance strategic thinking.",
        coachingProgram2: "<strong>Personal Growth Paths:</strong> Customized programs for individuals seeking to develop specific skills, overcome obstacles, and achieve personal milestones.",
        coachingProgram3: "<strong>Team Development & Cohesion:</strong> Workshops and coaching sessions focused on improving team dynamics, communication, collaboration, and collective performance.",
        coachingProgram4: "<strong>Change Management Coaching:</strong> Guiding organizations and individuals through periods of transition, ensuring smooth adaptation and successful implementation of new strategies.",
        coachingProgram5: "<strong>Innovation & Creativity Workshops:</strong> Fostering a culture of innovation within your organization, encouraging creative problem-solving and out-of-the-box thinking.",
        whyChooseCoaching: "Why Choose Grafamara Coaching?",
        whyChooseCoachingText: "Our certified coaches bring a wealth of experience and a deep understanding of human potential. We employ proven methodologies and a personalized approach, ensuring that each program is aligned with your unique objectives. Whether you are an aspiring leader, a seasoned executive, or a team looking to elevate its performance, Grafamara Coaching is your partner in achieving lasting transformation.",
        exploreCoachingPrograms: "Explore Our Coaching Programs",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Consulting for modern media platforms, including YouTube, blogs, and podcasts, to build your brand's voice.",
        multimediaExample: "<em>Example: YouTube Channel Growth Strategy.</em>",
        multimediaServicesInclude: "Our Multimedia Services Include:",
        multimediaService1: "<strong>YouTube Channel Management & Growth Strategy:</strong> We offer end-to-end support for your YouTube presence, including content strategy, video production guidance, SEO optimization, audience engagement, and growth analytics. Our success with **Bosolo TV**, growing from 0 to over 500,000 subscribers, is a testament to our expertise.",
        multimediaService2: "<strong>Podcast Production & Distribution:</strong> From concept development and scriptwriting to recording, editing, and distribution, we handle every aspect of podcast creation, ensuring high-quality audio and broad reach.",
        multimediaService3: "<strong>Blog Content Creation & Strategy:</strong> Crafting engaging and SEO-optimized blog posts that resonate with your target audience, drive traffic, and establish your thought leadership.",
        multimediaService4: "<strong>Technical Setup & Studio Optimization:</strong> Assisting with the setup of professional recording studios, recommending equipment, and optimizing your technical workflow for seamless content production.",
        multimediaService5: "<strong>Digital Media Consulting:</strong> Providing strategic advice on leveraging various digital media platforms to achieve your communication and marketing objectives.",
        whyChooseMultimedia: "Why Choose Grafamara Multimedia?",
        whyChooseMultimediaText: "Our team combines creative vision with technical expertise to deliver multimedia solutions that stand out. We understand the nuances of digital storytelling and audience engagement, ensuring your content not only reaches but also captivates your target market. Partner with Grafamara Multimedia to transform your ideas into influential digital experiences.",
        discussMultimediaProject: "Discuss Your Multimedia Project",
        contactTitle: "Contact Us",
        contactMessageIntro: "For quick service, you can send us an email or WhatsApp:",
        contactEmail: "grafamara@outlook.com",
        contactPhone: "+4915734925028",
        lastName: "Last Name:",
        firstName: "First Name:",
        email: "Email Address:",
        phone: "Phone Number:",
        sendMessage: "Send Message",
        partnersTitle: "Our Partners",
        kashandel: "Kashandel",
        kashandelText: "A leading provider of innovative business solutions.",
        absy: "ABSY TV",
        absyText: "Your source for engaging and high-quality video content.",
        sam: "8Sam.ev",
        samText: "Pioneering the future of event management technology.",
        copyright: "&copy; 2025 Grafamara. All Rights Reserved.",
        ourPartners: "Our Partners:",
        learnMore: "entdecke"
    },
    fr: {
        learnMore: "entdecke"
    },
    de: {
        learnMore: "entdecke"
    },
    fr: {
        home: "Accueil",
        about: "À propos",
        history: "Notre histoire",
        services: "Nos services",
        partners: "Nos partenaires",
        contact: "Contact",
        heroTitle: "Grafamara : Votre Pont vers l'Excellence Numérique",
        heroSubtitle: "Des solutions pionnières pour un monde connecté",
        discoverServices: "Découvrez nos services",
        aboutTitle: "À propos de nous",
        aboutSubtitle: "Notre Engagement : Bâtir des Ponts Numériques",
        aboutParagraph1: "Chez <b>Grafamara</b>, nous sommes bien plus qu'une société de conseil en informatique — nous sommes des <b>architectes de la transformation</b>, des <b>catalyseurs de croissance</b> et des <b>bâtisseurs de connexions transcontinentales</b>.",
        aboutParagraph2: "Fondée en <b>Allemagne en 2017</b>, Grafamara s'est rapidement imposée comme un acteur de confiance dans le paysage du conseil, grâce à une approche axée sur l'<b>innovation</b>, la <b>fiabilité</b> et une solide compréhension des <b>dynamiques du marché mondial</b>. Notre équipe d'experts passionnés transforme les défis technologiques complexes en opportunités stratégiques adaptées à votre vision et à vos objectifs.",
        aboutParagraph3: "Ce qui nous distingue, c'est notre <b>positionnement unique au carrefour de l'Europe et de l'Afrique</b>. Nous sommes profondément convaincus de l'immense potentiel inexploité de la <b>République Démocratique du Congo (RDC)</b> — une nation vibrante avec une population jeune et connectée, et un fort appétit pour l'innovation numérique.",
        aboutParagraph4: "Grafamara s'engage à favoriser des <b>partenariats durables</b>, permettant aux entreprises et institutions européennes d'<b>explorer et d'investir</b> dans les opportunités émergentes à travers la RDC. Parallèlement, nous donnons aux <b>entreprises et institutions publiques congolaises</b> les moyens d'atteindre l'<b>excellence numérique</b> et de s'aligner sur les <b>meilleures pratiques mondiales</b>.",
        aboutParagraph5: "De plus, nous offrons un <b>accompagnement personnalisé</b> à tous les individus et entrepreneurs qui souhaitent <b>investir, collaborer, acheter ou vendre avec des entreprises européennes</b>. Que vous cherchiez à établir un partenariat, à poursuivre des opportunités académiques, à ouvrir un compte bancaire, à demander un visa, ou à lancer une entreprise — <b>Grafamara sera à vos côtés dès le premier jour</b>. Nous vous aide à <b>naviguer les processus administratifs</b> avec clarté et nous assurons que vous fassiez les bons choix dès le départ.",
        aboutParagraph6: "Notre travail est ancré dans <b>quatre valeurs fondamentales</b>:<br> <b>Intégrité</b> — Des conseils transparents fondés sur la confiance et l'éthique<br> <b>Innovation</b> — Des solutions créatives, pérennes et centrées sur l'utilisateur<br> <b>Excellence</b> — Des standards élevés dans chaque projet et chaque partenariat<br> <b>Partenariat</b> — Des collaborations à long terme qui créent un réel impact",
        aboutParagraph7: "En choisissant Grafamara, vous choisissez un <b>partenaire qui non seulement comprend vos besoins techniques</b>, mais qui est aussi <b>profondément connecté aux réalités culturelles, sociales et économiques des régions que nous servons</b>.",
        aboutParagraph8: "Laissez-nous vous aider à naviguer l'avenir avec clarté, confiance et succès.",
        historyTitle: "Notre histoire",
        historySubtitle: "De 2017 à Aujourd'hui : Bâtir l'Avenir Numérique",
        historyText: "L'aventure Grafamara a débuté en 2017 en Allemagne, animée par une vision claire : démystifier la technologie et la rendre accessible, sécurisée et profitable pour tous. Ce qui a commencé comme une initiative passionnée s'est rapidement transformé en une société de conseil en informatique reconnue, grâce à notre engagement inébranlable envers l'excellence et l'innovation. Dès nos débuts, nous nous sommes concentrés sur la cybersécurité, anticipant les défis d'un monde de plus en plus connecté.",
        servicesTitle: "Nos services",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Conseils stratégiques en cybersécurité, IA et gestion des risques pour protéger et pérenniser votre entreprise.",
        advisoryExample: "<em>Exemple : Audit d'intégration de l'IA et tests de pénétration.</em>",
        advisoryServicesInclude: "Nos Services de Conseil Comprennent :",
        advisoryService1: "<strong>Stratégie et Mise en Œuvre de la Cybersécurité :</strong> Développement de cadres de sécurité complets, mise en œuvre de systèmes de protection avancés et garantie de la conformité aux normes internationales (par exemple, RGPD, ISO 27001).",
        advisoryService2: "<strong>Audit et Éthique de l'Intégration de l'IA :</strong> Évaluation des implications de sécurité de l'adoption de l'IA, audit des systèmes d'IA pour les biais et les vulnérabilités, et établissement de directives éthiques en matière d'IA.",
        advisoryService3: "<strong>Gestion des Risques et Continuité des Activités :</strong> Identification des risques numériques potentiels, élaboration de stratégies d'atténuation et création de plans de continuité des activités robustes pour minimiser les perturbations.",
        advisoryService4: "<strong>Tests d'Intrusion et Évaluations des Vulnérabilités :</strong> Identification proactive des faiblesses de vos systèmes et applications par le biais d'attaques simulées et d'évaluations de sécurité approfondies.",
        advisoryService5: "<strong>Formation de Sensibilisation à la Sécurité :</strong> Donner à vos employés les connaissances et les compétences nécessaires pour reconnaître et réagir aux cybermenaces, transformant ainsi votre personnel en votre plus forte défense.",
        whyChooseAdvisory: "Pourquoi Choisir Grafamara Advisory ?",
        whyChooseAdvisoryText: "Notre équipe d'experts certifiés en cybersécurité et en IA apporte une connaissance approfondie de l'industrie et une approche proactive de la défense numérique. Nous ne nous contentons pas d'identifier les problèmes ; nous fournissons des stratégies exploitables et un soutien pratique pour mettre en œuvre des solutions durables. Partenaires avec nous pour transformer vos vulnérabilités numériques en atouts stratégiques.",
        requestConsultation: "Demandez une Consultation en Cybersécurité",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Programmes de développement personnel et professionnel conçus pour libérer le potentiel et favoriser la réussite.",
        coachingExample: "<em>Exemple : Coaching de dirigeants et parcours de croissance personnelle.</em>",
        coachingProgramsInclude: "Nos Programmes de Coaching Comprennent :",
        coachingProgram1: "<strong>Coaching Exécutif :</strong> Coaching individuel pour les leaders et les cadres afin d'affiner les compétences en leadership, d'améliorer la prise de décision et de renforcer la pensée stratégique.",
        coachingProgram2: "<strong>Parcours de Croissance Personnelle :</strong> Programmes personnalisés pour les individus cherchant à développer des compétences spécifiques, à surmonter les obstacles et à atteindre des jalons personnels.",
        coachingProgram3: "<strong>Développement et Cohésion d'Équipe :</strong> Ateliers et séances de coaching axés sur l'amélioration de la dynamique d'équipe, de la communication, de la collaboration et de la performance collective.",
        coachingProgram4: "<strong>Coaching en Gestion du Changement :</strong> Accompagnement des organisations et des individus à travers les périodes de transition, assurant une adaptation en douceur et une mise en œuvre réussie des nouvelles stratégies.",
        coachingProgram5: "<strong>Ateliers d'Innovation et de Créativité :</strong> Favoriser une culture de l'innovation au sein de votre organisation, encourageant la résolution créative de problèmes et la pensée hors des sentiers battus.",
        whyChooseCoaching: "Pourquoi Choisir Grafamara Coaching ?",
        whyChooseCoachingText: "Notre équipe d'experts certifiés en cybersécurité et en IA apporte une connaissance approfondie de l'industrie et une approche proactive de la défense numérique. Nous ne nous contentons pas d'identifier les problèmes ; nous fournissons des stratégies exploitables et un soutien pratique pour mettre en œuvre des solutions durables. Partenaires avec nous pour transformer vos vulnérabilités numériques en atouts stratégiques.",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Conseil pour les plateformes médiatiques modernes, y compris YouTube, les blogs et les podcasts, afin de développer la voix de votre marque.",
        multimediaExample: "<em>Exemple : Stratégie de croissance et de mise en place d'une chaîne YouTube.</em>",
        multimediaServicesInclude: "Nos Services Multimédia Comprennent :",
        multimediaService1: "<strong>Gestion de Chaîne YouTube & Stratégie de Croissance :</strong> Nous offrons un soutien de bout en bout pour votre présence sur YouTube, y compris la stratégie de contenu, les conseils de production vidéo, l'optimisation SEO, l'engagement du public et l'analyse de croissance. Notre succès avec **Bosolo TV**, passant de 0 à plus de 500 000 abonnés, témoigne de notre expertise.",
        multimediaService2: "<strong>Production & Distribution de Podcasts :</strong> Du développement du concept et de l'écriture de scénarios à l'enregistrement, l'édition et la distribution, nous gérons chaque aspect de la création de podcasts, garantissant un son de haute qualité et une large portée.",
        multimediaService3: "<strong>Création de Contenu de Blog & Stratégie :</strong> Rédaction d'articles de blog engageants et optimisés pour le référencement qui résonnent avec votre public cible, génèrent du trafic et établissent votre leadership éclairé.",
        multimediaService4: "<strong>Configuration Technique & Optimisation de Studio :</strong> Aide à la mise en place de studios d'enregistrement professionnels, recommandation d'équipements et optimisation de votre flux de travail technique pour une production de contenu fluide.",
        multimediaService5: "<strong>Conseil en Médias Numériques :</strong> Fournir des conseils stratégiques sur l'exploitation de diverses plateformes de médias numériques pour atteindre vos objectifs de communication et de marketing.",
        whyChooseMultimedia: "Pourquoi Choisir Grafamara Multimedia ?",
        whyChooseMultimediaText: "Notre équipe combine une vision créative avec une expertise technique pour offrir des solutions multimédia qui se démarquent. Nous comprenons les nuances de la narration numérique et de l'engagement du public, garantissant que votre contenu non seulement atteint mais aussi captive votre marché cible. Partenaires avec Grafamara Multimedia pour transformer vos idées en expériences numériques influentes.",
        discussMultimediaProject: "Discutez de Votre Projet Multimédia",
        contactTitle: "Contactez-nous",
        contactMessageIntro: "Pour être servi rapidement, vous pouvez nous envoyer un email ou WhatsApp :",
        contactEmail: "grafamara@outlook.com",
        contactPhone: "+4915734925028",
        lastName: "Nom de famille :",
        firstName: "Prénom :",
        email: "Adresse électronique :",
        phone: "Numéro de téléphone :",
        sendMessage: "Envoyer le message",
        partnersTitle: "Nos partenaires",
        kashandel: "Kashandel",
        kashandelText: "Un fournisseur de premier plan de solutions commerciales innovantes.",
        absy: "ABSY TV",
        absyText: "Votre source de contenu vidéo engageant et de haute qualité.",
        sam: "8Sam.ev",
        samText: "Pionnier de l'avenir de la technologie de gestion d'événements.",
        copyright: "&copy; 2025 Grafamara. Tous droits réservés.",
        ourPartners: "Nos partenaires :"
    },
    de: {
        home: "Startseite",
        about: "Über uns",
        history: "Unsere Geschichte",
        services: "Unsere Dienstleistungen",
        partners: "Unsere Partner",
        contact: "Kontakt",
        heroTitle: "Grafamara: Ihre Brücke zur Digitalen Exzellenz",
        heroSubtitle: "Wegweisende Lösungen für eine vernetzte Welt",
        discoverServices: "Entdecken Sie unsere Dienstleistungen",
        aboutTitle: "Über uns",
        aboutSubtitle: "Unser Engagement: Digitale Brücken bauen",
        aboutParagraph1: "Bei <b>Grafamara</b> sind wir mehr als nur ein IT-Beratungsunternehmen – wir sind <b>Architekten der Transformation</b>, <b>Katalysatoren für Wachstum</b> und <b>Erbauer transkontinentaler Verbindungen</b>.",
        aboutParagraph2: "Gegründet in <b>Deutschland im Jahr 2017</b>, hat sich Grafamara dank eines scharfen Fokus auf <b>Innovation</b>, <b>Zuverlässigkeit</b> und ein solides Verständnis der <b>globalen Marktdynamik</b> schnell als vertrauenswürdiger Akteur in der Beratungslandschaft etabliert. Unser Team leidenschaftlicher Experten verwandelt komplexe technologische Herausforderungen in strategische Chancen, die auf Ihre Vision und Ziele zugeschnitten sind.",
        aboutParagraph3: "Was uns auszeichnet, ist unsere <b>einzigartige Positionierung an der Schnittstelle von Europa und Afrika</b>. Wir sind zutiefst überzeugt vom riesigen, ungenutzten Potenzial der <b>Demokratischen Republik Kongo (DRK)</b> – einer lebendigen Nation mit einer jungen, vernetzten Bevölkerung und einem starken Appetit auf digitale Innovation.",
        aboutParagraph4: "Grafamara engagiert sich für die Förderung <b>nachhaltiger Partnerschaften</b>, die es europäischen Unternehmen und Institutionen ermöglichen, die aufstrebenden Chancen in der DRK zu <b>erkunden und zu investieren</b>. Gleichzeitig befähigen wir <b>kongolesische Unternehmen und öffentliche Institutionen</b>, <b>digitale Exzellenz</b> zu erreichen und sich an den <b>besten internationalen Praktiken</b> auszurichten.",
        aboutParagraph5: "Darüber hinaus bieten wir <b>persönliche Beratung</b> für alle Einzelpersonen und Unternehmer an, die mit europäischen Unternehmen <b>investieren, zusammenarbeiten, kaufen oder verkaufen</b> möchten. Egal, ob Sie eine Partnerschaft aufbauen, akademische Möglichkeiten verfolgen, ein Bankkonto eröffnen, ein Visum beantragen oder ein Geschäftsvorhaben starten möchten – <b>Grafamara steht Ihnen vom ersten Tag an zur Seite</b>. Wir helfen Ihnen, <b>administrative Prozesse</b> klar zu navigieren und stellen sicher, dass Sie von Anfang an die richtigen Schritte unternehmen.",
        aboutParagraph6: "Unsere Arbeit basiert auf <b>vier Kernwerten</b>:<br> <b>Integrität</b> — Transparente Beratung, die auf Vertrauen und Ethik basiert<br> <b>Innovation</b> — Kreative, zukunftssichere und benutzerzentrierte Lösungen<br> <b>Exzellenz</b> — Hohe Standards in jedem Projekt und jeder Partnerschaft<br> <b>Partnerschaft</b> — Langfristige Kooperationen, die echte Wirkung erzielen",
        aboutParagraph7: "Indem Sie Grafamara wählen, entscheiden Sie sich für einen <b>Partner, der nicht nur Ihre technischen Bedürfnisse versteht</b>, sondern auch <b>tief in den kulturellen, sozialen und wirtschaftlichen Realitäten der Regionen verwurzelt ist, die wir bedienen</b>.",
        aboutParagraph8: "Lassen Sie uns Ihnen helfen, die Zukunft mit Klarheit, Zuversicht und Erfolg zu navigieren.",
        historyTitle: "Unsere Geschichte",
        historySubtitle: "Von 2017 bis Heute: Die Digitale Zukunft Bauen",
        historyText: "Die Grafamara-Reise begann 2017 in Deutschland, angetrieben von einer klaren Vision: Technologie zu entmystifizieren und für jedermann zugänglich, sicher und profitabel zu machen. Was als leidenschaftliche Initiative begann, entwickelte sich dank unseres unerschütterlichen Engagements für Exzellenz und Innovation schnell zu einem anerkannten IT-Beratungsunternehmen. Von Anfang an konzentrierten wir uns auf Cybersicherheit und antizipierten die Herausforderungen einer zunehmend vernetzten Welt.",
        servicesTitle: "Unsere Dienstleistungen",
        advisoryTitle: "Grafamara Advisory",
        advisoryText: "Strategische Beratung in Cybersicherheit, KI und Risikomanagement, um Ihr Unternehmen zu schützen und zukunftssicher zu machen.",
        advisoryExample: "<em>Beispiel: KI-Integrationsprüfung & Penetrationstests.</em>",
        advisoryServicesInclude: "Unsere Beratungsleistungen umfassen:",
        advisoryService1: "<strong>Cybersicherheitsstrategie & Implementierung:</strong> Entwicklung umfassender Sicherheitsrahmen, Implementierung fortschrittlicher Schutzsysteme und Sicherstellung der Einhaltung internationaler Standards (z.B. DSGVO, ISO 27001).",
        advisoryService2: "<strong>KI-Integrationsprüfung & Ethik:</strong> Bewertung der Sicherheitsauswirkungen der KI-Einführung, Prüfung von KI-Systemen auf Verzerrungen und Schwachstellen sowie Festlegung ethischer KI-Richtlinien.",
        advisoryService3: "<strong>Risikomanagement & Geschäftskontinuität:</strong> Identifizierung potenzieller digitaler Risiken, Entwicklung von Minderungsstrategien und Erstellung robuster Geschäftskontinuitätspläne zur Minimierung von Unterbrechungen.",
        advisoryService4: "<strong>Penetrationstests & Schwachstellenanalysen:</strong> Proaktive Identifizierung von Schwachstellen in Ihren Systemen und Anwendungen durch simulierte Angriffe und gründliche Sicherheitsbewertungen.",
        advisoryService5: "<strong>Schulungen zur Sicherheitsbewusstsein:</strong> Befähigung Ihrer Mitarbeiter mit dem Wissen und den Fähigkeiten, Cyberbedrohungen zu erkennen und darauf zu reagieren, wodurch Ihre Belegschaft zu Ihrer stärksten Verteidigung wird.",
        whyChooseAdvisory: "Warum Grafamara Advisory wählen?",
        whyChooseAdvisoryText: "Unser Team aus zertifizierten Cybersicherheits- und KI-Experten verfügt über fundiertes Branchenwissen und einen proaktiven Ansatz zur digitalen Verteidigung. Wir identifizieren nicht nur Probleme; wir bieten umsetzbare Strategien und praktische Unterstützung bei der Implementierung dauerhafter Lösungen. Arbeiten Sie mit uns zusammen, um Ihre digitalen Schwachstellen in strategische Stärken zu verwandeln.",
        requestConsultation: "Fordern Sie eine Cybersicherheitsberatung an",
        coachingTitle: "Grafamara Coaching",
        coachingText: "Programme zur persönlichen und beruflichen Entwicklung, die darauf abzielen, Potenziale freizusetzen und den Erfolg zu fördern.",
        coachingExample: "<em>Beispiel: Executive Coaching & Personal Growth Paths.</em>",
        coachingProgramsInclude: "Unsere Coaching-Programme umfassen:",
        coachingProgram1: "<strong>Executive Coaching:</strong> Einzelcoaching für Führungskräfte und Manager zur Verfeinerung von Führungsqualitäten, Verbesserung der Entscheidungsfindung und Stärkung des strategischen Denkens.",
        coachingProgram2: "<strong>Persönliche Wachstumswege:</strong> Maßgeschneiderte Programme für Einzelpersonen, die spezifische Fähigkeiten entwickeln, Hindernisse überwinden und persönliche Meilensteine erreichen möchten.",
        coachingProgram3: "<strong>Teamentwicklung & Zusammenhalt:</strong> Workshops und Coaching-Sitzungen zur Verbesserung der Teamdynamik, Kommunikation, Zusammenarbeit und kollektiven Leistung.",
        coachingProgram4: "<strong>Change Management Coaching:</strong> Begleitung von Organisationen und Einzelpersonen durch Übergangsphasen, um eine reibungslose Anpassung und erfolgreiche Umsetzung neuer Strategien zu gewährleisten.",
        coachingProgram5: "<strong>Innovations- und Kreativitäts-Workshops:</strong> Förderung einer Innovationskultur in Ihrem Unternehmen, Ermutigung zu kreativer Problemlösung und unkonventionellem Denken.",
        whyChooseCoaching: "Warum Grafamara Coaching wählen?",
        whyChooseCoachingText: "Unsere zertifizierten Coaches verfügen über einen reichen Erfahrungsschatz und ein tiefes Verständnis des menschlichen Potenzials. Wir wenden bewährte Methoden und einen personalisierten Ansatz an, um sicherzustellen, dass jedes Programm auf Ihre individuellen Ziele abgestimmt ist. Ob Sie eine aufstrebende Führungskraft, ein erfahrener Manager oder ein Team sind, das seine Leistung steigern möchte, Grafamara Coaching ist Ihr Partner für eine dauerhafte Transformation.",
        exploreCoachingPrograms: "Entdecken Sie unsere Coaching-Programme",
        multimediaTitle: "Grafamara Multimedia",
        multimediaText: "Beratung für moderne Medienplattformen, einschließlich YouTube, Blogs und Podcasts, um die Stimme Ihrer Marke aufzubauen.",
        multimediaExample: "<em>Beispiel: Einrichtungs- und Wachstumsstrategie für YouTube-Kanäle.</em>",
        multimediaServicesInclude: "Unsere Multimedia-Dienstleistungen umfassen:",
        multimediaService1: "<strong>YouTube-Kanalverwaltung & Wachstumsstrategie:</strong> Wir bieten End-to-End-Unterstützung für Ihre YouTube-Präsenz, einschließlich Inhaltsstrategie, Videoproduktionsberatung, SEO-Optimierung, Zielgruppenbindung und Wachstumsanalysen. Unser Erfolg mit **Bosolo TV**, das von 0 auf über 500.000 Abonnenten angewachsen ist, ist ein Beweis für unsere Expertise.",
        multimediaService2: "<strong>Podcast-Produktion & -Distribution:</strong> Von der Konzeptentwicklung und dem Schreiben von Drehbüchern bis hin zur Aufnahme, Bearbeitung und Distribution kümmern wir uns um jeden Aspekt der Podcast-Erstellung, um eine hohe Audioqualität und eine große Reichweite zu gewährleisten.",
        multimediaService3: "<strong>Blog-Inhaltserstellung & -Strategie:</strong> Erstellung ansprechender und SEO-optimierter Blog-Beiträge, die bei Ihrer Zielgruppe Anklang finden, Traffic generieren und Ihre Vordenkerrolle etablieren.",
        multimediaService4: "<strong>Technisches Setup & Studio-Optimierung:</strong> Unterstützung bei der Einrichtung professioneller Aufnahmestudios, Empfehlung von Geräten und Optimierung Ihres technischen Workflows für eine reibungslose Inhaltsproduktion.",
        multimediaService5: "<strong>Digitale Medienberatung:</strong> Bereitstellung strategischer Beratung zur Nutzung verschiedener digitaler Medienplattformen, um Ihre Kommunikations- und Marketingziele zu erreichen.",
        whyChooseMultimedia: "Warum Grafamara Multimedia wählen?",
        whyChooseMultimediaText: "Unser Team kombiniert kreative Vision mit technischem Fachwissen, um Multimedia-Lösungen zu liefern, die herausragen. Wir verstehen die Nuancen des digitalen Storytellings und der Zielgruppenbindung und stellen sicher, dass Ihre Inhalte Ihr Zielpublikum nicht nur erreichen, sondern auch fesseln. Arbeiten Sie mit Grafamara Multimedia zusammen, um Ihre Ideen in einflussreiche digitale Erlebnisse zu verwandeln.",
        discussMultimediaProject: "Besprechen Sie Ihr Multimedia-Projekt",
        contactTitle: "Kontaktieren Sie uns",
        contactMessageIntro: "Für schnellen Service können Sie uns eine E-Mail oder WhatsApp senden:",
        contactEmail: "grafamara@outlook.com",
        contactPhone: "+4915734925028",
        lastName: "Nachname:",
        firstName: "Vorname:",
        email: "E-Mail-Adresse:",
        phone: "Telefonnummer:",
        sendMessage: "Nachricht senden",
        partnersTitle: "Unsere Partner",
        kashandel: "Kashandel",
        kashandelText: "Ein führender Anbieter von innovativen Geschäftslösungen.",
        absy: "ABSY TV",
        absyText: "Ihre Quelle für ansprechende und qualitativ hochwertige Videoinhalte.",
        sam: "8Sam.ev",
        samText: "Wegbereiter für die Zukunft der Event-Management-Technologie.",
        copyright: "&copy; 2025 Grafamara. Alle Rechte vorbehalten.",
        ourPartners: "Unsere Partner:"
    }
};